defmodule SpdxExpression.DataGenerator do
  @version "3.28.0"

  def run do
    root = Path.expand("..", __DIR__)
    input_dir = Path.join([root, "priv", "spdx", @version])

    licenses =
      input_dir
      |> Path.join("licenses.json")
      |> load_entries!("licenses", "licenseId")

    exceptions =
      input_dir
      |> Path.join("exceptions.json")
      |> load_entries!("exceptions", "licenseExceptionId")

    assert_counts!(licenses, 727, 32, "licenses")
    assert_counts!(exceptions, 84, 1, "exceptions")

    output = Path.join([root, "lib", "spdx_expression", "data.ex"])
    File.mkdir_p!(Path.dirname(output))
    File.write!(output, render(licenses, exceptions))

    case System.cmd("mix", ["format", output], cd: root, stderr_to_stdout: true) do
      {_output, 0} -> :ok
      {command_output, status} -> raise "mix format failed (#{status}):\n#{command_output}"
    end

    IO.puts("Generated #{Path.relative_to(output, root)}")
  end

  defp load_entries!(path, collection_key, id_key) do
    document = path |> File.read!() |> Jason.decode!()

    unless document["licenseListVersion"] == @version do
      raise "#{path} is not SPDX License List #{@version}"
    end

    entries =
      document
      |> Map.fetch!(collection_key)
      |> Enum.map(fn entry ->
        id = Map.fetch!(entry, id_key)
        {String.downcase(id), {id, Map.fetch!(entry, "isDeprecatedLicenseId")}}
      end)
      |> Enum.sort_by(&elem(&1, 0))

    if map_size(Map.new(entries)) != length(entries) do
      raise "#{path} contains duplicate case-insensitive identifiers"
    end

    entries
  end

  defp assert_counts!(entries, total, deprecated, label) do
    actual_deprecated = Enum.count(entries, fn {_key, {_id, value}} -> value end)

    unless length(entries) == total and actual_deprecated == deprecated do
      raise "unexpected #{label} counts: total=#{length(entries)} deprecated=#{actual_deprecated}"
    end
  end

  defp render(licenses, exceptions) do
    """
    # Generated by scripts/generate_spdx_data.exs from SPDX License List #{@version}.
    # Do not edit by hand.
    defmodule SpdxExpression.Data do
      @moduledoc false

      @license_list_version #{@version |> inspect()}

      @licenses %{
    #{render_entries(licenses)}
      }

      @exceptions %{
    #{render_entries(exceptions)}
      }

      @spec license_list_version() :: String.t()
      def license_list_version, do: @license_list_version

      @spec lookup_license(String.t()) :: {String.t(), boolean()} | nil
      def lookup_license(lowercase_id), do: Map.get(@licenses, lowercase_id)

      @spec lookup_exception(String.t()) :: {String.t(), boolean()} | nil
      def lookup_exception(lowercase_id), do: Map.get(@exceptions, lowercase_id)

      @spec license_count() :: non_neg_integer()
      def license_count, do: map_size(@licenses)

      @spec exception_count() :: non_neg_integer()
      def exception_count, do: map_size(@exceptions)
    end
    """
  end

  defp render_entries(entries) do
    entries
    |> Enum.map_join(",\n", fn {key, value} -> "    #{inspect(key)} => #{inspect(value)}" end)
  end
end

SpdxExpression.DataGenerator.run()
